name: Build and Release
on:
  push:
    branches:
      - seismic
      - feature/**

jobs:
  build-and-release:
    name: Build and Release Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-14]
        arch: [x86_64, arm64]
        exclude:
          - os: macos-latest
            arch: x86_64  # Exclude x86_64 for macos-latest
          - os: macos-14
            arch: arm64  # Exclude arm64 for macos-14

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up dependencies
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y build-essential cmake python3 python3-pip zlib1g-dev libboost-all-dev libssl-dev ccache
          elif [ "${{ matrix.os }}" = "macos-latest" ] || [ "${{ matrix.os }}" = "macos-14" ]; then
            brew install cmake boost openssl ccache
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            choco install cmake boost-msvc
          fi

      - name: Update Git submodules
        run: git submodule update --init --recursive

      - name: Build Seismic Solidity
        shell: bash
        run: |
          mkdir build
          cd build
          if [ "${{ matrix.os }}" = "macos-latest" ] || [ "${{ matrix.os }}" = "macos-14" ]; then
            cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} -DUSE_Z3=OFF -DPEDANTIC=OFF
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            cmake .. -G "Visual Studio 16 2019" -A ${{ matrix.arch }} -DCMAKE_BUILD_TYPE=Release -DUSE_Z3=OFF -DPEDANTIC=OFF
          else
            cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_Z3=OFF -DPEDANTIC=OFF
          fi
          make -j2

      - name: Archive binary
        shell: bash
        run: |
          cd build
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            tar -czvf seismic-solc-macos-arm64.tar.gz solc
          elif [ "${{ matrix.os }}" = "macos-14" ]; then
            tar -czvf seismic-solc-macos-x86_64.tar.gz solc
          elif [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            tar -czvf seismic-solc-linux-${{ matrix.arch }}.tar.gz solc
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a seismic-solc-windows-${{ matrix.arch }}.zip solc.exe
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: "Release for ${{ github.ref_name }}"
          body: "Automated release for commit ${{ github.sha }}."
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/seismic-solc-${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'windows-latest' && 'windows' || matrix.os == 'macos-latest' && 'macos-arm64' || 'macos-x86_64' }}-${{ matrix.os != 'macos-latest' && matrix.os != 'macos-14' && matrix.arch || '' }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}
          asset_name: seismic-solc-${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'windows-latest' && 'windows' || matrix.os == 'macos-latest' && 'macos-arm64' || 'macos-x86_64' }}-${{ matrix.os != 'macos-latest' && matrix.os != 'macos-14' && matrix.arch || '' }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}
          asset_content_type: ${{ matrix.os == 'windows-latest' && 'application/zip' || 'application/gzip' }}